name: Publish

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Download build
        uses: dawidd6/action-download-artifact@v2
        with:
          name: actions_artifacts
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Setup build for SPA routing
        run: |
          cp ./dist/index.html ./dist/404.html
          rm ./dist/index.html

      - name: Get PR number
        run: |
          echo "PR=$(cat env | grep "prev.event.number" | awk -F '=' '{print $2}')" >> $GITHUB_ENV
          echo "BUILD_URL=$(echo ${{ github.repository }} | sed -r 's/\//\.github\.io\//g')" >> $GITHUB_ENV

      - name: Deploy build to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
          git-config-name: "keksobot"
          git-config-email: "github+keksobot@htmlacademy.ru"
          target-folder: ${{ env.PR }}
          commit-message: "‚úîÔ∏è –°–±–æ—Ä–∫–∞ #${{ env.PR }}"

      - name: Comment PR
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            –í–∞—à –ø—É–ª—Ä–µ–∫–≤–µ—Å—Ç –æ–ø—É–±–ª–∏–∫–æ–≤–∞–Ω. –ü–æ—Å–º–æ—Ç—Ä–µ—Ç—å –º–æ–∂–Ω–æ [–∑–¥–µ—Å—å](https://${{ env.BUILD_URL }}/${{ env.PR }}/)
          pr_number: ${{ env.PR }}

      - name: Comment CodeSandbox Link
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ## üèñÔ∏è CodeSandbox Preview
            [![Open in CodeSandbox](https://img.shields.io/badge/Open%20in-CodeSandbox-blue?style=for-the-badge&logo=codesandbox)](https://codesandbox.io/p/github/${{ github.event.workflow_run.head_repository.full_name }}/${{ github.event.workflow_run.head_branch }})
          pr_number: ${{ env.PR }}

